### ISSUE TITLE
qualname fails with user defined decorators (on python2.x).

### ISSUE THREAD

**Issue by mgilson** [wbolster/qualname#4]
```python

import functools
from qualname import qualname

def decorator(f):
    @functools.wraps(f)
    def wrapper(*args, **kwargs):
        return f(*args, **kwargs)
    return wrapper

@decorator
def h():
    pass

print(qualname(h))
print(h.__qualname__)
```

The following code produces different results on python2.x and python3.x.  On python3.x:

```
$ python3 ~/sandbox/qq.py
h
h
```

However, on python2.x, we get:

```
$ python ~/sandbox/qq.py
decorator.<locals>.wrapper
Traceback (most recent call last):
  File "/Users/mgilson/sandbox/qq.py", line 19, in <module>
    print(h.__qualname__)
AttributeError: 'function' object has no attribute '__qualname__'
```

The attribute error is expected, however, we see that `qualname(h)` evaluates to `'decorator.<locals>.wrapper'` whereas on python3.x, it evaluated to `'h'` (presumably because `functools.wraps` updates `__qualname__` on python3.x and `qualname` just uses `__qualname__` if it's there).

I'm not certain that I know a good solution to this problem, but then again -- I probably wouldn't have thought of parsing the AST to get the qualname in the first place...

**Comment by alexmojaki** [comment]
This comes down to the fact that `qualname` uses the line number attribute of the code attribute of the function, and `functools.wraps` doesn't change the code object. Even `inspect` is affected by this:

```python
import functools
import inspect

def decorator(f):
    @functools.wraps(f)
    def wrapper(*args, **kwargs):
        return f(*args, **kwargs)
    return wrapper

@decorator
def h():
    pass

print(inspect.getsource(h))  # prints the source of wrapper
```

However, [the `wrapt` library](http://wrapt.readthedocs.io/en/latest/decorators.html) solves the problem:

```python
import inspect
import wrapt
from qualname import qualname

@wrapt.decorator
def decorator(wrapped, instance, args, kwargs):
    return wrapped(*args, **kwargs)

@decorator
def h():
    pass

print(qualname(h))  # h
print(inspect.getsource(h))  # source of h
```

**Comment by piccolbo** [comment]
Do people agree this shows a functools.wraps bug? Should we report?

**Comment by alexmojaki** [comment]
@piccolbo it's fixed in Python 3, `wraps` adds a `__wrapped__` attributed pointing to the original function, and `inspect` knows to check for this (even following a chain if necessary).

I suppose `qualname` could offer a function which patches `functools` to add `__wrapped__`, and then `qualname` itself could follow the chain. The user would have to make sure they call the patching function nice and early.

**Comment by piccolbo** [comment]
Good to know but doesn't solve the problem for 2.7 laggards (me included).

**Comment by alexmojaki** [comment]
The fact that the feature/fix is in Python 3 means the Python developers know about the problem and don't want to fix it in 2. Probably because it would change the behaviour of a lot of programs.

**Comment by wbolster** [comment]
i agree with @alexmojaki. python 2 is legacy python with many known issues. this small toy project is hack to (partially) work around one of those, but it's not perfect and will never be.

tbh, in 2018 nobody should start using this (fun) project on py2. use py3 instead and rejoice. :)

**Comment by piccolbo** [comment]
Not my choice to be on py2 for this specific project. And I am always
honest ;)
